project/urls.py
# Third-Party
# Django
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import include
from django.urls import path
from django.views.defaults import bad_request
from django.views.defaults import page_not_found
from django.views.defaults import permission_denied
from django.views.defaults import server_error
from django.views.generic import TemplateView
# First-Party
from sentry_sdk import last_event_id

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name='root/robots.txt',
        content_type='text/plain"',
    )),
    path('sitemap.txt', TemplateView.as_view(
        template_name='root/sitemap.txt',
        content_type='text/plain"',
    )),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

def handler400(request, *args, **argv):
    return render(
        request,
        'root/400.html',
        context={},
        status=400,
    )

def handler403(request, *args, **argv):
    return render(
        request,
        'root/403.html',
        context={},
        status=403,
    )

def handler404(request, *args, **argv):
    return render(
        request,
        'root/404.html',
        context={},
        status=404,
    )

def handler500(request, *args, **argv):
    return render(
        request,
        'root/500.html',
        {
            'sentry_dsn': settings.SENTRY_DSN,
            'sentry_event_id': last_event_id(),
        },
        status=500,
    )

project/app/models.py
# First-Party
import datetime

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.gis.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models.constraints import UniqueConstraint
from django_fsm import FSMIntegerField
from django_fsm import transition
from django_fsm_log.decorators import fsm_log_by
from hashid_field import HashidAutoField
from model_utils import Choices

# Local
from .managers import UserManager


class Account(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    name = models.CharField(
        max_length=100,
        blank=False,
    )
    is_public = models.BooleanField(
        default=False,
    )
    is_spouse = models.BooleanField(
        default=False,
    )
    address = models.CharField(
        max_length=512,
        blank=True,
        default='',
    )
    voter_json = models.JSONField(
        blank=True,
        null=True,
    )
    place = models.CharField(
        max_length=255,
        blank=True,
        default='',
        editable=True,
    )
    is_precise = models.BooleanField(
        null=True,
    )
    point = models.PointField(
        null=True,
        blank=True,
    )
    geocode = models.JSONField(
        blank=True,
        null=True,
    )
    picture = models.ImageField(
        null=False,
        blank=False,
        default='wapa/avatar',
    )
    notes = models.TextField(
        max_length=2000,
        blank=True,
        default='',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    user = models.OneToOneField(
        'app.User',
        on_delete=models.CASCADE,
        related_name='account',
        unique=True,
    )
    zone = models.ForeignKey(
        'app.Zone',
        on_delete=models.SET_NULL,
        related_name='account',
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.name}"


class Attendee(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    is_confirmed = models.BooleanField(
        default=False,
    )
    account = models.ForeignKey(
        'app.Account',
        on_delete=models.CASCADE,
        related_name='attendees',
        null=False,
        blank=False,
    )
    event = models.ForeignKey(
        'app.Event',
        on_delete=models.CASCADE,
        related_name='attendees',
        null=False,
        blank=False,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    def __str__(self):
        return f"{self.id}"

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=[
                    'account',
                    'event',
                ],
                name='unique_attendee',
            )
        ]


class Comment(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    STATE = Choices(
        (-10, 'denied', 'Denied'),
        (-5, 'archived', 'Archived'),
        (0, 'pending', 'Pending'),
        (10, 'approved', 'Approved'),
    )
    state = FSMIntegerField(
        choices=STATE,
        default=STATE.pending,
    )
    is_featured = models.BooleanField(
        default=False,
    )
    content = models.TextField(
        max_length=2000,
        blank=False,
    )
    account = models.ForeignKey(
        'app.Account',
        on_delete=models.CASCADE,
        related_name='comments',
        null=False,
        blank=False,
    )
    issue = models.ForeignKey(
        'app.Issue',
        on_delete=models.CASCADE,
        related_name='comments',
        null=False,
        blank=False,
    )

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=[
                    'account',
                    'issue',
                ],
                name='unique_comment',
            )
        ]
        ordering = (
            '-created',
        )

    @property
    def wordcount(self):
        words = self.content.split(" ")
        return len(words)

    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return f"{self.account.name}"

    @fsm_log_by
    @transition(field=state, source=[STATE.pending, STATE.denied], target=STATE.approved)
    def approve(self):
        from .tasks import send_approval_email
        from .tasks import send_comment
        send_approval_email.delay(self)
        if self.account.zone and self.account.zone.num !=2:
            send_comment.delay(self)
        return

    @fsm_log_by
    @transition(field=state, source=[STATE.pending, STATE.approved], target=STATE.denied)
    def deny(self):
        from .tasks import send_denial_email
        send_denial_email.delay(self.account)
        return


    @fsm_log_by
    @transition(field=state, source=[STATE.denied, STATE.approved], target=STATE.pending)
    def pend(self):
        return


class Event(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    name = models.CharField(
        max_length=100,
        blank=False,
    )
    description = models.TextField(
        max_length=2000,
        blank=True,
        default='',
    )
    date = models.DateField(
        default=datetime.date.today,
    )
    datetime = models.DateTimeField(
        null=True,
        blank=False,
    )
    location = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )
    notes = models.TextField(
        max_length=2000,
        blank=True,
        default='',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return f"{self.name}"


class Issue(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    STATE = Choices(
        (-5, 'archived', 'Archived'),
        (0, 'pending', 'Pending'),
        (10, 'active', 'Active'),
    )
    state = FSMIntegerField(
        choices=STATE,
        default=STATE.pending,
    )
    name = models.CharField(
        max_length=100,
        blank=False,
    )
    description = models.TextField(
        max_length=2000,
        blank=True,
        default='',
    )
    recipient_name = models.CharField(
        max_length=100,
        blank=True,
    )
    recipient_emails = ArrayField(
        models.EmailField(
        ),
        null=True,
        blank=True,
    )
    date = models.DateField(
        default=datetime.date.today,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = (
            '-created',
        )


class Isat(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    SUBJECT = Choices(
        (10, 'english', 'English'),
        (20, 'math', 'Math'),
        (30, 'science', 'Science'),
    )
    subject = models.IntegerField(
        choices=SUBJECT,
        null=True,
    )
    GRADE = Choices(
        (1, 'all', 'All'),
        (3, 'third', 'Third'),
        (4, 'fourth', 'Fourth Grade'),
        (5, 'fifth', 'Fifth Grade'),
        (6, 'sixth', 'Sixth Grade'),
        (7, 'seventh', 'Seventh Grade'),
        (8, 'eighth', 'Eighth Grade'),
        (10, 'high', 'High School'),
    )
    grade = models.IntegerField(
        choices=GRADE,
        null=True,
    )
    advanced_note = models.CharField(
        max_length=10,
        blank=True,
    )
    proficient_note = models.CharField(
        max_length=10,
        blank=True,
    )
    basic_note = models.CharField(
        max_length=10,
        blank=True,
    )
    below_note = models.CharField(
        max_length=10,
        blank=True,
    )
    advanced = models.FloatField(
        null=True,
        blank=True,
    )
    proficient = models.FloatField(
        null=True,
        blank=True,
    )
    basic = models.FloatField(
        null=True,
        blank=True,
    )
    below = models.FloatField(
        null=True,
        blank=True,
    )
    year = models.IntegerField(
        null=False,
        blank=False,
    )
    school = models.ForeignKey(
        'app.School',
        on_delete=models.CASCADE,
        related_name='isats',
        null=True,
        blank=False,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    def __str__(self):
        return f"{self.id}"


class School(models.Model):
    id = HashidAutoField(
        primary_key=True,
    )
    full = models.CharField(
        max_length=100,
        blank=False,
    )
    name = models.CharField(
        max_length=100,
        blank=False,
    )
    school_id = models.IntegerField(
        null=True,
        blank=True,
    )
    location_id = models.IntegerField(
        null=True,
        blank=True,
    )
    gis_id = models.IntegerField(
        null=True,
        blank=True,
    )
    is_traditional = models.BooleanField(
        default=False,
    )
    KIND = Choices(
        (10, 'elementary', 'Elementary School'),
        (20, 'middle', 'Middle School'),
        (30, 'high', 'High School'),
    )
    kind = models.IntegerField(
        choices=KIND,
        default=0,
    )
    address_raw = models.CharField(
        max_length=512,
        blank=True,
        default='',
    )
    phone_raw = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )
    point = models.PointField(
        null=True,
        blank=True,
    )
    enrollment = models.IntegerField(
        null=True,
        blank=True,
    )
    size = models.IntegerField(
        null=True,
        blank=True,
    )

project/app/forms.py
# Django
from django import forms
from django.contrib.auth.forms import UserChangeForm as UserChangeFormBase
from django.contrib.auth.forms import UserCreationForm as UserCreationFormBase
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from django.utils.safestring import mark_safe

# Local
from .models import Account
from .models import Attendee
from .models import Comment
from .models import Isat
from .models import Student
from .models import User
from .widgets import AddressWidget

StudentFormSet = inlineformset_factory(
    Account,
    Student,
    fields=[
        'school',
        'grade',
    ],
    can_delete=True,
    extra=1,
)


class ConfirmForm(forms.Form):
    confirm = forms.BooleanField(
        required=True,
    )


class AttendeeForm(forms.ModelForm):
    class Meta:
        model = Attendee
        fields = [
            'is_confirmed',
            # 'account',
            # 'event',
        ]
        labels = {
            "is_confirmed": "Yes I'll Attend",
        }


class IsatForm(forms.ModelForm):
    class Meta:
        model = Isat
        fields = [
            'subject',
            'grade',
            'year',
            'advanced_note',
            'proficient_note',
            'basic_note',
            'below_note',
            'advanced',
            'proficient',
            'basic',
            'below',
            'school',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control h-25',
                    'placeholder': 'Comments',
                    'rows': 5,
                }
            ),
        }

    def clean_content(self):
        content= self.cleaned_data['content']
        words = content.split(" ")
        for word in words:
            if any([
                word.startswith("http"),
                word.startswith("www"),
            ]):
                raise ValidationError(
                    "Links are not allowed in comments."
                )
        return content


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'school',
            'grade',
        ]
        widgets = {
            # 'text': forms.Textarea(
            #     attrs={
            #         'class': 'form-control h-25',
            #         'placeholder': 'Comments',
            #         'rows': 5,
            #     }
            # ),
        }
        help_texts = {
            'school': "School attending 2022-23.",
            'grade': "Grade for 2022-23.",
        }


class SearchForm(forms.Form):
    query = forms.CharField(
        required=True,
        max_length=200,
    )


class ZoneForm(forms.Form):
    address = forms.CharField(
        required=True,
        # widget=AddressWidget(
        #     attrs={'style': "width: 600px;"}
        # ),
    )


class AccountAdminForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = [
        'picture',
        'name',
        'address',
        'geocode',
        'is_precise',
        'place',
        'point',
        'is_public',
        'is_spouse',
        'zone',
        'user',        ]
        widgets = {
            'address': AddressWidget(
                attrs={'style': "width: 600px;"}
            ),
        }

        help_texts = {
            'name': mark_safe("Please update to your full, real name."),
            'address': mark_safe("Please provide your <strong>residence address</strong>, which will remain <strong>private and confidential</strong>."),
            'email': mark_safe("We do not sell, share, or spam you."),
        }


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = [
            'name',
            'is_public',
            'is_spouse',
            'zone',
        ]
        labels = {
            "is_public": "I Choose to be Public",
            "is_spouse": "I Represent My Spouse",
        }
        help_texts = {
            'name': mark_safe("Please provide your <strong>real full name</strong>, which remains private unless you explcitly choose to be public."),
            'is_public': mark_safe("Making your name public enables <a href='/comments'>Comments</a>."),
            'is_spouse': "If your spouse shares your position, click here and we'll double your support.",
            'zone': mark_safe("Indicating your Zone helps us direct your comment to the right Trustee.  <a href='#' data-toggle='modal' data-target='#zoneMap'>Zone Map</a>."),
        }

    def clean(self):
        cleaned_data = super().clean()
        is_public = cleaned_data.get("is_public")
        name = cleaned_data.get("name")
        last_name = name.partition(" ")[2]
        full_name = False
        if last_name:
            if len(last_name) > 1 and not last_name.endswith('.'):
                full_name = True
        if is_public and not full_name:
            raise ValidationError(
                "You must provide your full name to be public."
            )


class UserCreationForm(UserCreationFormBase):
    """
    Custom user creation form for Auth0
    """

    # Bypass password requirement
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_unusable_password()
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = [
            'username',
        ]


class UserChangeForm(UserChangeFormBase):
    """
    Custom user change form for Auth0
    """

    class Meta:
        model = User
        fields = [
            'username',
        ]

project/app/templates/pages/comments.html
{% extends '_base.html' %}
{% load bootstrap4 %}
{% load app_tags %}
{% load static %}
{% load cloudinary %}

{% block title %}Comments{% endblock title %}

{% block robots %}
  <meta name="ROBOTS" content="NOINDEX" />
{% endblock robots %}

{% block content %}

  {% comment %}
  <section class='my-5'>
    <h2>
      Comments
    </h2>
  </section>
  {% endcomment %}
  {% if issue %}
    {% if not account.is_public %}
      <section class='col-md-12 mt-5'>
        <div class='card'>
          <h4 class='card-header'>
            Private Account
          </h4>
          <div class="card-body">
            <div class='card-title'>
            </div>
            <div class='card-text'>
              <p class='lead col-md-8'>
                You need to make your name public in order to make a public comment.  You can make this change at your <a href='{% url "account" %}'>Account Page</a>, and then return here to submit a comment.
              </p>
            </div>
          </div>
        </div>
      </section>
    {% elif comment.get_state_display == 'Approved' %}
      <section class='col-md-12 mt-5'>
        <div class='card'>
          <h4 class='card-header'>
            Your Comment
          </h4>
          <div class="card-body">
            <div class='card-title'>
            </div>
            <div class='card-text'>
              <blockquote class="blockquote mb-0">
                <p>
                  "{{comment.content}}"
                </p>
                <footer class="blockquote-footer">Posted on {{comment.updated}}</footer>
              </blockquote>
            </div>
          </div>
          <div class='card-footer'>
            <ul class='list-inline'>
              <li class='list-inline-item'>
                {% bootstrap_button "Share Your Comment on Facebook" button_type='link' size='small' button_class='btn-primary' extra_classes='ml-3 mt-3' id='facebook-share-button'%}
              </li>
              <li class='list-inline-item'>
                {% bootstrap_button "Share Your Comment via Text" button_type='link' size='small' button_class='btn-success' extra_classes='ml-3 mt-3' id='text-share-button'%}
              </li>
            </ul>
          </div>
        </div>
        <p class='float-right'>
          <a class='text-danger align-bottom' href='{% url "comment-delete" comment.id %}'><small>Delete Comment</small></a>
        </p>
      </section>
    {% elif comment.get_state_display == 'Denied' %}
      <section class='col-md-12 mt-5'>
        <form method='post'>
          {% csrf_token %}
          <div class='card'>
            <h4 class='card-header'>
              Your Comment
            </h4>
            <div class="card-body">
              <div class='card-title'>
                <p class='lead'>
                  Your Comment was Not Approved
                </p>
                <p>
                  We generally only allow comments that are respectful and constrained to the issue at-hand.  Please edit your comment according to these guidelines, save, and then we can approve it.
                </p>
                <ul class='list-styled'>
                  <li>Remain respectful and on-topic.</li>
                  <li>Be concise.</li>
                  <li>No personal attacks.</li>
                </ul>
              </div>
              <div class='card-text'>
                  {% bootstrap_form_errors form %}
                  {% bootstrap_field form.content show_help=True show_label=False %}
              </div>
            </div>
            <div class='card-footer'>
              <ul class='list-inline'>
                <li class='list-inline-item'>
                  {% bootstrap_button "Save!" button_type='submit' size='large' %}</li>
                <li class='list-inline-item'>
                  {% bootstrap_button "Cancel" button_type='link' href="/comments" size='large' button_class='btn-outline-dark' extra_classes='ml-3'%}
                </li>
              </ul>
            </div>
          </div>
        </form>
        <p class='float-right'>
          <a class='text-danger align-bottom' href='{% url "comment-delete" comment.id %}'><small>Delete Comment</small></a>
        </p>
      </section>
    {% elif comment.get_state_display == 'Archived' %}
    {% elif comment.get_state_display == 'Pending' %}
      <section class='col-md-12 mt-5'>
        <form method='post'>
          {% csrf_token %}
          <div class='card'>
            <h4 class='card-header'>
              Your Comment
            </h4>
            <div class="card-body">
              <div class='card-title'>
                <p class='lead'>
                  Your Comment is Pending
                </p>
                <p class='col-md-8'>
                  Due to the highly charged nature of this particular issue we are requiring approval of all comments prior to posting.  Please forgive the delay; we'll do our best to get to each comment as quickly as possible, generally within a day or two.
                </p>
              </div>
              <div class='card-text mt-5 col-md-8'>
                  {% bootstrap_form_errors form %}
                  {% bootstrap_field form.content show_help=True show_label=False %}
              </div>
            </div>
            <div class='card-footer'>
              <div class='col-md-12'>
                <ul class='list-inline'>
                  <li class='list-inline-item'>
                    {% bootstrap_button "Save" button_type='submit' size='large' %}</li>
                  <li class='list-inline-item'>
                {% bootstrap_button "Cancel" button_type='link' href="/comments" size='large' button_class='btn-outline-dark' extra_classes='ml-3'%}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </form>
        <p class='float-right'>
          <a class='text-danger align-bottom' href='{% url "comment-delete" comment.id %}'><small>Delete Comment</small></a>
        </p>
      </section>
    {% else %}
      <section class='col-md-12 mt-5'>
        <form method='post'>
          {% csrf_token %}
          <div class='card'>
            <h4 class='card-header'>
              Submit Comment
            </h4>
            <div class="card-body">
              <div class='card-title'>
                <p class='lead'>
                  We'll post your comment and forward a copy to your Zone Trustee.  Here are some suggestions:
                </p>
                <ul class='list-styled'>
                  {{issue.description|safe}}
                </ul>
              </div>
              <p>
                And as always: <strong>No personal attacks.</strong>  Remain respectful and on-topic.  Be concise.
              </p>
              <div class='card-text'>
                  {% bootstrap_form_errors form %}
                  {% bootstrap_field form.content show_help=True show_label=False %}
              </div>
            </div>
            <div class='card-footer'>
              <ul class='list-inline'>
                <li class='list-inline-item'>
                  {% bootstrap_button "Send!" button_type='submit' size='large' %}</li>
                <li class='list-inline-item'>
              {% bootstrap_button "Cancel" button_type='link' href="/comments" size='large' button_class='btn-outline-dark' extra_classes='ml-3'%}
                </li>
              </ul>
            </div>
          </div>
        </form>
      </section>
    {% endif %}

  <section class='my-5 col-md-12'>
    <div class='card'>
      <h4 class='card-header'>
        All Public Comments
      </h4>
      <div class="card-body">
        <div class='card-text'>
          <table class='table'>
            <thead>
              <tr class='row'>
                <th scope='col' class='col-5'>Name</th>
                <th scope='col' class='col-7'>Comments</th>
              </tr>
            </thead>
            <tbody>
              {% for comment in comments %}
                <tr class='row'>
                  <td class='col-5'>
                    <ul class='list-inline'>
                      <li class='list-inline-item align-top'>
                        {% cloudinary comment.account.picture.name AVATAR %}<br>
                      </li>
                      <li class='list-inline-item'>
                        <strong>{{comment.account.name}}</strong><br>
                        {% for student in comment.account.students.all %}
                          {% if student.school.get_kind_display == 'Elementary School' %}
                            <span class='badge badge-danger badge-pill'>{{ student.school.name }} {{student.ord|default:"" }}</span><br>
                          {% elif student.school.get_kind_display == 'Middle School' %}
                            <span class='badge badge-success badge-pill'>{{ student.school.name }} {{student.ord|default:"" }}</span><br>
                          {% elif student.school.get_kind_display == 'High School' %}
                            <span class='badge badge-info badge-pill'>{{ student.school.name }} {{student.ord|default:"" }}</span><br>
                          {% endif %}
                        {% endfor %}
                      </li>
                    </ul>
                  </td>
                  <td class='col-7'>
                    {% if comment.wordcount < 60 %}
                      {{comment.content}}
                    {% else %}
                      <div class="collapse show" id="comment-{{comment.id}}">
                        {{comment.content|truncatewords:60}}
                      </div>
                      <div class="collapse" id="comment-{{comment.id}}">
                        {{comment.content}}
                      </div>
                      <a data-toggle="collapse" href="#comment-{{comment.id}}"><small>more</small></a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
  {% else %}
  <section class='my-5'>
    <h2>
      Comments
    </h2>
  </section>
  <section class='my-5'>

    <p class='lead col-lg-8'>
      Currently there are no open issues available for comments.  To see your prior comments, please visit your <a href='{% url "dashboard" %}'>Dashboard</a> page.
    </p>

  {% endif %}
{% endblock content %}

{% block scripts %}
  {% if comment.get_state_display == 'Approved' %}
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId            : '{% get_env_var "FACEBOOK_CLIENT_ID" %}',
          autoLogAppEvents : true,
          xfbml            : true,
          version          : 'v11.0'
        });
      };
    </script>
    <script>
      const FBbutton = document.querySelector('#facebook-share-button');
      FBbutton.addEventListener('click', async () => {
        FB.ui({
          method: "share",
          href: "https://www.westadaparents.com",
          quote: "Back to Normal School"
        }, function(response){});
      });
    </script>

    <script>
      const toShare = {
        title: "Start Normal",
        // text: "{{comment.content|escapejs}}",
        text: "It's time for our kids to be normal again.",
        url: "https://www.westadaparents.com",
      };
      const button = document.querySelector('#text-share-button');
      button.addEventListener('click', async () => {
        try {
          await navigator.share(toShare); // Will trigger the native "share" feature
          button.textContent = 'Thank You -- Share Again!';
        }
        catch(err) {
          Sentry.captureException(err);
          $("#text-share-button").replaceWith( "<p class='align-middle ml-3 mt-3'>Copy/Paste '<strong>https://www.westadaparents.com</strong>' in your Text or Email</p>" );
        }
      });
    </script>
  {% endif %}
{% endblock scripts %}

project/app/templates/pages/confirm.html
{% extends '_base.html' %}

{% load bootstrap4 %}

{% block robots %}
  <meta name="ROBOTS" content="NOINDEX" />
{% endblock robots %}

{% block title %}Confirm Voter Record{% endblock title %}

{% block content %}
  <section class='my-5'>
    <h2>
      Confirm Voter Record
    </h2>
  </section>
  {% comment %}
  <section>
    <p class='lead'>
      Please confirm the following voter record.
    </p>
  </section>
  {% endcomment %}
  <section class-'my-5 col-lg-6'>
    <div class='card'>
      <div class='card-body'>
        <ul class='list-unstyled'>
          <li>{{voter.name}}</li>
          <li>{{voter.location|upper}}</li>
        </ul>
      </div>
    </div>
  </section>
  <section class='my-5'>
    <form method='post' role='form'>
      {% csrf_token %}
      {% bootstrap_form_errors form %}
      {% bootstrap_field form.confirm %}
      <ul class='list-inline'>
        <li class='list-inline-item mb-3 pr-3'>{% bootstrap_button "I Confirm This is My Voter Record" button_type='submit' button_class='btn btn-success btn-lg' %}</li>
        {% url "search" as search_url %}
        <li class='list-inline-item'>{% bootstrap_button "This Isn't Me -- Search Again" button_type='link' href=search_url size='large' button_class='btn-outline-dark' %}</li>
      </ul>
    </form>
  </section>
  {% comment %}
  <section class='my-5 col-lg-6'>
    <p class='text-danger'>
      WARNING: Any person who supplies any information to impersonate a registered voter is guilty of perjury which is punishable by imprisonment and a fine of up to $50,000.
    </p>
  </section>
  {% endcomment %}

{% endblock content %}